services:
  - type: web
    name: askmydocs-backend
    env: python
    pythonVersion: "3.11.0"
    rootDir: backend
    buildCommand: pip install --no-cache-dir -r requirements-minimal.txt
    startCommand: python test_server.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        sync: false
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1