services:
  - type: web
    name: askmydocs-backend
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: GOOGLE_API_KEY
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false
    runtime: python3.11
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1